[tools]
"cargo:cargo-llvm-cov" = "0.6.16"
rust = { version = "nightly-2025-07-01", components = "llvm-tools-preview" }

[tasks]
test = "cargo llvm-cov && cargo llvm-cov report --lcov --output-path lcov.info && cargo llvm-cov report --html"