version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - cargo build --release

  test:
    desc: Run tests with coverage
    cmds:
      - cargo test

  coverage:
    desc: Generate code coverage report
    cmds:
      - cargo llvm-cov --all-features --workspace
      - cargo llvm-cov report --lcov --output-path lcov.info
      - cargo llvm-cov report --html

  coverage-codecov:
    desc: Generate code coverage report for Codecov
    cmds:
      - cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json

  fmt:
    desc: Check code formatting
    cmds:
      - cargo fmt --check

  lint:
    desc: Run clippy linter
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  fmt-fix:
    desc: Fix code formatting
    cmds:
      - cargo fmt

  dev:
    desc: Development build
    cmds:
      - cargo build

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
