name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        task: [build, test, format, lint]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-llvm-cov
        if: matrix.task == 'test'
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build the project
        if: matrix.task == 'build'
        run: task build

      - name: Run tests with coverage
        if: matrix.task == 'test'
        run: task coverage-codecov

      - name: Upload coverage to Codecov
        if: matrix.task == 'test'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true

      - name: Check code formatting
        if: matrix.task == 'format'
        run: task fmt

      - name: Run clippy linter
        if: matrix.task == 'lint'
        run: task lint
