name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        task: [build, test, format, lint]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@2deec96fc0de605d114d3860f29d1d066ad4151e # stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x

      - name: Cache dependencies
        uses: Swatinem/rust-cache@f0deed1 # latest

      - name: Build the project
        if: matrix.task == 'build'
        run: task build

      - name: Run tests with coverage
        if: matrix.task == 'test'
        run: task test

      - name: Check code formatting
        if: matrix.task == 'format'
        run: task fmt

      - name: Run clippy linter
        if: matrix.task == 'lint'
        run: task lint