name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        task: [build, test, format, lint]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336d9b35a # stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x

      - name: Cache dependencies
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

      - name: Build the project
        if: matrix.task == 'build'
        run: task build

      - name: Run tests with coverage
        if: matrix.task == 'test'
        run: task test

      - name: Check code formatting
        if: matrix.task == 'format'
        run: task fmt

      - name: Run clippy linter
        if: matrix.task == 'lint'
        run: task lint